version: '3.8'

services:
  clib-cms-admin: &clib-cms-admin
    build: .
    volumes:
      - '.:/clib-cms-admin'
      - packages:/node_modules/
    ports:
      - 4000:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

volumes: 
  packages: